test:
  timeout: 5000
  maximized: true
  headless: false
  browser: chrome
  version: 87

ui:
  url: https://appfollow.io/ru/

api:
  url: https://api.appfollow.io/
  secret: Basic eXBWZlVEV3NFRENGUFY3NXBkakw6